# https://www.appveyor.com/docs/appveyor-yml/

environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 10
    - nodejs_version: 8

version: "{build}"

build: off

deploy: off

branches:
  only:
    - master

clone_depth: 1

skip_tags: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm test

cache:
  - '%APPDATA%\npm-cache\ -> appveyor.yml,package.json,package-lock.json'
